### ISSUE TITLE
ScratchVar is not defined

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algo-builder#387]
Upon the last update, during runtime testing, I get:

![image](https://user-images.githubusercontent.com/26761348/122908310-45ff3980-d354-11eb-8301-7bb4fb411988.png)

**Comment by ratik21** [comment]
@Lumene98 could you please share a little more context with your issue (`algob` version, ssc code, ..) ? note: make sure you're using linked(yarn link) master code.

from looking at the error (`NameError: name ScratchVar is not defined`):
We are [using](https://github.com/scale-it/algo-builder/blob/master/examples/nft/assets/nft_approval.py#L48) `SratchVar` in our [`examples/nft`](https://github.com/scale-it/algo-builder/tree/master/examples/nft), and it's working fine. I also tested with `pipenv (sync + shell)`, it is working fine as well.

Previously we were using a specific commit in our pipfile to support ScratchVar, as at that time pyTEAL hadn't released that code, but now since it is released, we're simple using the latest pyTEAL version in our pipfile.

BDW - could you test by passing [`version = 3`](https://github.com/scale-it/algo-builder/blob/master/examples/permissioned-token/assets/controller.py#L214) in your compileTeal(..), i.e `compileTeal(program, mode, version = 3)`?

**Comment by Lumene98** [comment]
It works with pipenv, it's probably related to my installation
